<a href="https://colab.research.google.com/github/karim-mttk/DataScienceEssentials/blob/master/exercises_book_Python__for_Data_Analysis_Wes_Mckinney.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Chapter 4. NumPy Basics: Arrays and Vectorized Computation

### Intro

In [ ]:
import numpy as np

my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [ ]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 10.8 ms, sys: 11.2 ms, total: 22 ms
Wall time: 26.9 ms


In [ ]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 590 ms, sys: 236 ms, total: 826 ms
Wall time: 862 ms


In [ ]:
data = np.random.randn(2,3)
data

array([[ 1.12237829, -0.47522703, -1.18009433],
       [-0.13021116,  1.75794234, -0.25833538]])

In [ ]:
data.shape

(2, 3)

In [ ]:
data.dtype

dtype('float64')

In [ ]:
data1 = [6,7,8.8,9,102]
arr1 = np.array(data1)

arr1

array([  6. ,   7. ,   8.8,   9. , 102. ])

In [ ]:
data2 = [[7,8,9,4],[1,2,3,6]]
arr2 = np.array(data2)

arr2

array([[7, 8, 9, 4],
       [1, 2, 3, 6]])

In [ ]:
arr2.ndim

2

In [ ]:
arr2.shape

(2, 4)

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
#at times it will return garbage values
np.empty((2,3,2))

array([[[2.77808132e-316, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [ ]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
eye_array = np.eye(3,4)
eye_array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
#finding metadata with dtype
arr1 = np.array([1,2,3], dtype=np.float64)
arr2 = np.array([3,4,5], dtype=np.int32)
print(arr1.dtype, arr2.dtype)

float64 int32


In [ ]:
#casting into different types
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int64')

In [ ]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [ ]:
arr = np.array([1.1,2.22,3.56,89.7,777.7])
arr

array([  1.1 ,   2.22,   3.56,  89.7 , 777.7 ])

In [ ]:
arr.astype(np.int32)

array([  1,   2,   3,  89, 777], dtype=int32)

In [ ]:
#converting strings into numbers
numeric_strings = np.array(['1.23', '5.77','-9.57'], dtype=np.string_)

In [ ]:
numeric_strings.astype(float)

array([ 1.23,  5.77, -9.57])

In [ ]:
int_array = np.arange(10)
calibers = np.array([.22, .256, .343, .3535, .2525])

In [ ]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### Arithmetic with NumPy arrays

In [2]:
import numpy as np
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [3]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [4]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [6]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [8]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [9]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

### Basic Indexing and Slicing

In [12]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr[5]

5

In [14]:
#including 5 exlcuding 8
arr[5:8]

array([5, 6, 7])

In [16]:
#when a scalar value of 12 is added to the list it propagates
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [17]:
#arr_slice refers to the original array.arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [18]:
#if arr_slice is changed it will change the numbers in the original array
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [19]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [20]:
#one dimensional arrays
arr2d = np.array([[1,2,3],[4,6,5],[9,8,7]])
arr2d[2]

array([9, 8, 7])

In [21]:
arr2d[0][2]

3

In [22]:
arr2d[0,1]

2

In [24]:
#2x2x3
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [25]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])