<a href="https://colab.research.google.com/github/karim-mttk/DataScienceEssentials/blob/master/exercises_book_Python__for_Data_Analysis_Wes_Mckinney.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Chapter 4. NumPy Basics: Arrays and Vectorized Computation

### Intro

In [ ]:
import numpy as np

my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [ ]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 10.8 ms, sys: 11.2 ms, total: 22 ms
Wall time: 26.9 ms


In [ ]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 590 ms, sys: 236 ms, total: 826 ms
Wall time: 862 ms


In [ ]:
data = np.random.randn(2,3)
data

array([[ 1.12237829, -0.47522703, -1.18009433],
       [-0.13021116,  1.75794234, -0.25833538]])

In [ ]:
data.shape

(2, 3)

In [ ]:
data.dtype

dtype('float64')

In [ ]:
data1 = [6,7,8.8,9,102]
arr1 = np.array(data1)

arr1

array([  6. ,   7. ,   8.8,   9. , 102. ])

In [ ]:
data2 = [[7,8,9,4],[1,2,3,6]]
arr2 = np.array(data2)

arr2

array([[7, 8, 9, 4],
       [1, 2, 3, 6]])

In [ ]:
arr2.ndim

2

In [ ]:
arr2.shape

(2, 4)

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
#at times it will return garbage values
np.empty((2,3,2))

array([[[2.77808132e-316, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [ ]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
eye_array = np.eye(3,4)
eye_array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
#finding metadata with dtype
arr1 = np.array([1,2,3], dtype=np.float64)
arr2 = np.array([3,4,5], dtype=np.int32)
print(arr1.dtype, arr2.dtype)

float64 int32


In [ ]:
#casting into different types
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int64')

In [ ]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [ ]:
arr = np.array([1.1,2.22,3.56,89.7,777.7])
arr

array([  1.1 ,   2.22,   3.56,  89.7 , 777.7 ])

In [ ]:
arr.astype(np.int32)

array([  1,   2,   3,  89, 777], dtype=int32)

In [ ]:
#converting strings into numbers
numeric_strings = np.array(['1.23', '5.77','-9.57'], dtype=np.string_)

In [ ]:
numeric_strings.astype(float)

array([ 1.23,  5.77, -9.57])

In [ ]:
int_array = np.arange(10)
calibers = np.array([.22, .256, .343, .3535, .2525])

In [ ]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### Arithmetic with NumPy arrays

In [ ]:
import numpy as np
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [ ]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [ ]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [ ]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [ ]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

### Basic Indexing and Slicing

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[5]

5

In [ ]:
#including 5 exlcuding 8
arr[5:8]

array([5, 6, 7])

In [ ]:
#when a scalar value of 12 is added to the list it propagates
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [ ]:
#arr_slice refers to the original array.arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [ ]:
#if arr_slice is changed it will change the numbers in the original array
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [ ]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [11]:
#two dimensional arrays
arr2d = np.array([[1,2,3],[4,6,5],[9,8,7]])
arr2d[2]

array([9, 8, 7])

In [ ]:
arr2d[0][2]

3

In [ ]:
arr2d[0,1]

2

In [2]:
#2x2x3
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [3]:
import numpy as np
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr3d[0]=42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [5]:
arr3d[1,0]

array([7, 8, 9])

In [8]:
#indexing with slices
arr = np.array([1,2,4,5,6,7,8,9])
arr

array([1, 2, 4, 5, 6, 7, 8, 9])

In [9]:
arr[1:6]

array([2, 4, 5, 6, 7])

In [12]:
arr2d

array([[1, 2, 3],
       [4, 6, 5],
       [9, 8, 7]])

In [13]:
arr2d[:2]

array([[1, 2, 3],
       [4, 6, 5]])

In [14]:
arr2d[:2, 1:]

array([[2, 3],
       [6, 5]])

In [15]:
arr2d[1, :2]

array([4, 6])

In [16]:
arr2d[:2, 2]

array([3, 5])

In [17]:
arr2d[:, :1]

array([[1],
       [4],
       [9]])

In [18]:
arr2d[:2, 1:]=0

**Boolean indexing**


In [19]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7,4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [20]:
data

array([[ 1.41324703, -0.58086339,  1.57661034,  0.42093081],
       [-0.80469562,  0.54566044, -0.43009846,  1.08052405],
       [-0.17398587,  1.01023613, -0.69568596,  0.20283493],
       [ 0.31999561,  0.3962742 , -2.15510706, -0.61756668],
       [ 0.36452226, -0.25752538,  0.55042386,  1.90905741],
       [-1.98824358, -0.71096359,  0.15173161, -1.15920252],
       [ 2.71890914, -0.2699665 , -0.85680669,  0.46343396]])

In [21]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [22]:
data[names == 'Bob']

array([[ 1.41324703, -0.58086339,  1.57661034,  0.42093081],
       [ 0.31999561,  0.3962742 , -2.15510706, -0.61756668]])

In [24]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [25]:
data[mask]

array([[ 1.41324703, -0.58086339,  1.57661034,  0.42093081],
       [-0.17398587,  1.01023613, -0.69568596,  0.20283493],
       [ 0.31999561,  0.3962742 , -2.15510706, -0.61756668],
       [ 0.36452226, -0.25752538,  0.55042386,  1.90905741]])

In [26]:
data[data < 0] = 0

In [27]:
data

array([[1.41324703, 0.        , 1.57661034, 0.42093081],
       [0.        , 0.54566044, 0.        , 1.08052405],
       [0.        , 1.01023613, 0.        , 0.20283493],
       [0.31999561, 0.3962742 , 0.        , 0.        ],
       [0.36452226, 0.        , 0.55042386, 1.90905741],
       [0.        , 0.        , 0.15173161, 0.        ],
       [2.71890914, 0.        , 0.        , 0.46343396]])

In [ ]:
data[names != 'Joe'] = 7

**Transposing Arrays and Swapping Axes**

In [29]:
arr=np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
arr.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [31]:
arr.T

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
arr = np.random.randn(6, 3)
arr

array([[ 1.6381323 , -0.01916106,  0.03380774],
       [-1.38404103, -0.0112269 ,  0.6934335 ],
       [ 1.25315699,  0.15123706, -1.84174912],
       [-0.93613784, -0.3706007 ,  0.07900046],
       [-1.90531857,  0.18163917, -0.38476116],
       [ 0.46269558,  0.56789039,  0.14019864]])

In [33]:
np.dot(arr.T, arr)

array([[10.89012956,  0.43728713, -2.4883531 ],
       [ 0.43728713,  0.516203  , -0.30652149],
       [-2.4883531 , -0.30652149,  4.04797068]])

In [34]:
arr=np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [35]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [36]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [37]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

**Universal Functions: Fast Element-Wise Array Functions**

In [38]:
#unary functions
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [40]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [41]:
#binary functions add or max
x = np.random.randn(8)
y = np.random.randn(8)
x

array([-1.75254186,  0.87756237,  1.61154013, -0.43359112, -1.11698906,
        0.60161055, -0.83746258,  0.52047999])

In [42]:
y

array([-0.75324549, -0.57012819, -0.59898134,  0.01101418,  1.07567571,
        0.8994999 ,  1.0515847 ,  1.23587919])

In [43]:
np.maximum(x, y)

array([-0.75324549,  0.87756237,  1.61154013,  0.01101418,  1.07567571,
        0.8994999 ,  1.0515847 ,  1.23587919])

In [44]:
arr = np.random.randn(7)*5
arr

array([-0.05246305,  8.43957982, -4.59054379, -4.1204474 ,  6.63255701,
       -5.19641719, -8.24480972])

**Array-Oriented Programming with Arrays**