<a href="https://colab.research.google.com/github/karim-mttk/DataScienceEssentials/blob/main/exercises_book_Python__for_Data_Analysis_Wes_Mckinney.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Chapter 4. NumPy Basics: Arrays and Vectorized Computation

In [5]:
import numpy as np

my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [6]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 10.8 ms, sys: 11.2 ms, total: 22 ms
Wall time: 26.9 ms


In [7]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 590 ms, sys: 236 ms, total: 826 ms
Wall time: 862 ms


In [8]:
data = np.random.randn(2,3)
data

array([[ 1.12237829, -0.47522703, -1.18009433],
       [-0.13021116,  1.75794234, -0.25833538]])

In [9]:
data.shape

(2, 3)

In [11]:
data.dtype

dtype('float64')

In [12]:
data1 = [6,7,8.8,9,102]
arr1 = np.array(data1)

arr1

array([  6. ,   7. ,   8.8,   9. , 102. ])

In [14]:
data2 = [[7,8,9,4],[1,2,3,6]]
arr2 = np.array(data2)

arr2

array([[7, 8, 9, 4],
       [1, 2, 3, 6]])

In [15]:
arr2.ndim

2

In [16]:
arr2.shape

(2, 4)

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
#at times it will return garbage values
np.empty((2,3,2))

array([[[2.77808132e-316, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [21]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
eye_array = np.eye(3,4)
eye_array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [29]:
#finding metadata with dtype
arr1 = np.array([1,2,3], dtype=np.float64)
arr2 = np.array([3,4,5], dtype=np.int32)
print(arr1.dtype, arr2.dtype)

float64 int32


In [31]:
#casting into different types
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int64')

In [33]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [35]:
arr = np.array([1.1,2.22,3.56,89.7,777.7])
arr

array([  1.1 ,   2.22,   3.56,  89.7 , 777.7 ])

In [36]:
arr.astype(np.int32)

array([  1,   2,   3,  89, 777], dtype=int32)

In [38]:
#converting strings into numbers
numeric_strings = np.array(['1.23', '5.77','-9.57'], dtype=np.string_)

In [39]:
numeric_strings.astype(float)

array([ 1.23,  5.77, -9.57])

In [40]:
int_array = np.arange(10)
calibers = np.array([.22, .256, .343, .3535, .2525])

In [41]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
#upnext: Arithmetic with NumPy Arrays